from typing import Dict, Literal, Optional, Union, List
from pydantic import BaseModel, Field
       
formatters_types_description: str = f"""The formatter type of this field.
'Semperis.ReportTemplates.DataSource.DB.ADSyntaxFormatter, Semperis.ReportTemplates.DataSource.DB' for From_Syntax, To_Syntax ,
'Semperis.ReportTemplates.DataSource.DB.DBDateTimeFormatter, Semperis.ReportTemplates.DataSource.DB' for CollectionTime, OriginatingTime, Valid Until, ValidUntil,
'Semperis.ReportTemplates.DataSource.Data.DefaultFormatter, Semperis.ReportTemplates.DataSource.Data' for all other fields"""

formatters_names_description: str = """The formatter anme of this field.
'ADSyntax Formatting' for From_Syntax, To_Syntax ,
'Universal sortable date/time pattern' for CollectionTime, OriginatingTime, Valid Until, ValidUntil,
'No Formatting' for all other fields"""

class NonDNSSelectedFormatterSchema(BaseModel):
    DollarType: Literal[
        'Semperis.ReportTemplates.DataSource.DB.ADSyntaxFormatter, Semperis.ReportTemplates.DataSource.DB',
        'Semperis.ReportTemplates.DataSource.DB.DBDateTimeFormatter, Semperis.ReportTemplates.DataSource.DB',
        'Semperis.ReportTemplates.DataSource.Data.DefaultFormatter, Semperis.ReportTemplates.DataSource.Data'
    ] = Field(description=formatters_types_description)
    
    Name: Literal[
        'ADSyntax Formatting',
        'Universal sortable date/time pattern',
        'No Formatting'] = Field(description=formatters_names_description)

dns_fields_description: str = """The display fields in this DNS reports. Fields explanation:
AttributeName (Name of the changed attribute),
LastKnownParent (DN of the last known parent container),
LVRRef (Low version reference (version tracking)),
SID (Security Identifier),
From_IsStringValueXmlString (Whether the previous value was an XML string),
From_Meta_CreationTime (When this attribute value was created),
From_Meta_DeletionTime (When this attribute value was deleted),
From_Meta_HasData (Whether this field had data),
From_Meta_LastOriginatingChangeTime (When this value last changed),
From_Meta_LastOriginatingInvocationId (Invocation ID of the DC making the change),
From_Meta_LocalChangeUsn (Local USN when the change happened),
From_Meta_ObjectDn (DN of the object before change),
From_Meta_ObjectGuid (GUID of the object before change),
From_Meta_OriginatingChangeUsn (USN from the originating DC),
From_Meta_OriginatingServer (Server that originated the change),
From_Meta_Version (Version of the attribute value),
From_ResolveFlags (Flags describing resolution state),
From_Syntax (Data type of previous value) <-- Formatter is "ADSyntax Formatting",
From_BinaryBase64Value (Previous binary value, Base64 encoded),
From_StringValue (Previous value as string),
To_IsStringValueXmlString (Whether new value is XML string),
To_Meta_CreationTime (When this value was created),
To_Meta_DeletionTime (When this value was deleted),
To_Meta_HasData (Whether this field has data),
To_Meta_LastOriginatingChangeTime (When this value last changed),
To_Meta_LastOriginatingInvocationId (Invocation ID of the DC making the change),
To_Meta_LocalChangeUsn (Local USN when the change happened),
To_Meta_ObjectDn (DN after the change),
To_Meta_ObjectGuid (GUID after the change),
To_Meta_OriginatingChangeUsn (USN from the originating DC),
To_Meta_OriginatingServer (Server that originated the change),
To_Meta_Version (Version of the attribute),
To_ResolveFlags (Flags describing resolution state),
To_Syntax (Data type of new value) <-- Formatter is "ADSyntax Formatting",
To_BinaryBase64Value (New binary value, Base64 encoded),
To_StringValue (New value as string),
ClassName (Object class (eg, user, group, computer)),
DisplayName (User-friendly display name),
Distinguished Name (Full LDAP path identifying the object),
Object Guid (Unique GUID of the object),
SamAccountName (Pre-Windows 2000 logon name),
UPN (User Principal Name (user@domain)),
Version (Version of the record),
CollectionTime (When the data was collected) <-- Formatter is "Universal sortable date/time pattern",
ForestGenerationId (ID representing the forest replication generation),
Row Number (Row number in the report),
UserMatchCount (How many users matched this record),
ValidUntil (When this data expires) <-- Formatter is "Universal sortable date/time pattern",
DirSyncOperationType (Type of directory sync operation (add, modify, delete)),
ModificationType (Type of change (add, modify, delete)),
OriginatingServer (DC that made the change),
OriginatingTime (Time the change originated) <-- Formatter is "Universal sortable date/time pattern",
OriginatingUsers (User(s) who triggered the change),
OriginatingUserWorkstations (Workstations where change originated),
IsActionable (Whether this row requires action),
IsFirst (Whether this is the first change in a sequence),
IsLast (Whether this is the last change in a sequence),
IsPassword (Whether the change was to a password),
IsVirtual (Whether this is a virtual object)"""

class DNSResultColumnSchema(BaseModel):
    Name: Literal[
        "AttributeName",
        "LastKnownParent",
        "LVRRef",
        "SID",
        "From_IsStringValueXmlString",
        "From_Meta_CreationTime",
        "From_Meta_DeletionTime",
        "From_Meta_HasData",
        "From_Meta_LastOriginatingChangeTime",
        "From_Meta_LastOriginatingInvocationId",
        "From_Meta_LocalChangeUsn",
        "From_Meta_ObjectDn",
        "From_Meta_ObjectGuid",
        "From_Meta_OriginatingChangeUsn",
        "From_Meta_OriginatingServer",
        "From_Meta_Version",
        "From_ResolveFlags",
        "From_Syntax",
        "From_BinaryBase64Value",
        "From_StringValue",
        "To_IsStringValueXmlString",
        "To_Meta_CreationTime",
        "To_Meta_DeletionTime",
        "To_Meta_HasData",
        "To_Meta_LastOriginatingChangeTime",
        "To_Meta_LastOriginatingInvocationId",
        "To_Meta_LocalChangeUsn",
        "To_Meta_ObjectDn",
        "To_Meta_ObjectGuid",
        "To_Meta_OriginatingChangeUsn",
        "To_Meta_OriginatingServer",
        "To_Meta_Version",
        "To_ResolveFlags",
        "To_Syntax",
        "To_BinaryBase64Value",
        "To_StringValue",
        "ClassName",
        "DisplayName",
        "Distinguished Name",
        "Object Guid",
        "SamAccountName",
        "UPN",
        "Version",
        "CollectionTime",
        "ForestGenerationId",
        "Row Number",
        "UserMatchCount",
        "ValidUntil",
        "DirSyncOperationType",
        "ModificationType",
        "OriginatingServer",
        "OriginatingTime",
        "OriginatingUsers",
        "OriginatingUserWorkstations",
        "IsActionable",
        "IsFirst",
        "IsLast",
        "IsPassword",
        "IsVirtual"]                                 = Field(description=dns_fields_description)
    # TODO post processing- this is "$type"
    SelectedFormatter: NonDNSSelectedFormatterSchema = Field(description="The formatter to use for this display column")
    DollarType       : str                           = "Semperis.ReportTemplates.DataSource.DB.DBDataColumn, Semperis.ReportTemplates.DataSource.DB"
    Alias            : Optional[str]                 = Field(default=None, description="An alias the user wants to assign to this display column instead of the attribute's real name")